# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Davide Gallon
title: PhD student
email: davide.gallon@uni-muenster.de
website: www.github.com/davidegallon

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  davidegallon
# stackoverflow_username: 
# dribbble_username: 
# facebook_username: 
# flickr_username: 
# instagram_username: 
linkedin_username: davide-gallon-76203a148
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/Gallon-Davide.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Davide and I am a PhD student in Mathematics at the University of Münster - Cluster of Excellence Mathematics (Germany).
  #I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Research # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          ...
        description: | # this will include new lines to allow paragraphs
          Bla

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Hitachi Energy
        link: https://www.hitachienergy.com/
        # link_text: boringcompany.com
        sub_title: R&D Data Scientist
        caption: June 2022 - June 2023
        quote: >
         Inspire the next
        description: | # this will include new lines to allow paragraphs
         My primary responsibility was to design and implement innovative solutions to complex data-related problems, working closely with a international team of researchers and engineers.
         One of the major projects I have worked on is the development of a machine learning model to predict transformer's performance. The resulting model was integrated into the company's application.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Padua
        caption: October 2019 - March 2022
        sub_title: Master degree in Mathematical Engineering 
        description: | # this will include new lines to allow paragraphs
          Graduated with 110/110 cum laude.
          I have dedicated my studies to numerical methods for differential equations, dynamic simulations, neural networks for deep learning, numerical methods for big data, stochastic equations.
    content:
      - layout: left
        title: University of Padua
        caption: October 2016 - September 2019
        sub_title: Bachelor degree in Mathematics 
        description: | # this will include new lines to allow paragraphs
          ...
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
