# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Davide Gallon
title: PhD student
email: davide.gallon@uni-muenster.de
website: www.github.com/davidegallon

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: 
github_username:  davidegallon
scholar_username: citations?user=I9lLc9cAAAAJ&hl=it&oi=ao
# stackoverflow_username: 
# dribbble_username: 
# facebook_username: 
# flickr_username: 
# instagram_username: 
linkedin_username: davide-gallon-76203a148
# xing_username: 
# pinterest_username: 
# youtube_username: 
# googleplus_username: 
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Scholar link
  icon:  fab fa-google-scholar
  url: https://scholar.google.com/citations?user=I9lLc9cAAAAJ&hl=it
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons/google-scholar?f=classic&s=brands)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/Gallon-Davide.JPG
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Davide and I am a PhD student in Mathematics at the University of Münster - Cluster of Excellence Mathematics (Germany).
  

content:
  - title: Research # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Muenster - Cluster of Excellence Mathematics
        link: https://www.uni-muenster.de/AMM/show_perspage.shtml?id=1761
        link_text: University profile
        sub_title:  PhD in Applied Mathematics
        caption: July 2023 - Current
        #quote: >
        # Inspire the next
        description: | # this will include new lines to allow paragraphs
         The PhD focuses on exploring novel techniques in Machine Learning and their mathematical understanding. Supervisor: [Arnulf Jentzen](https://www.ajentzen.de/).

      - layout: top-middle
        title: Preprints
        description:  | # this will include new lines to allow paragraphs
          - **Davide Gallon**, Arnulf Jentzen, Philippe von Wurstemberger. *An overview of diffusion models for generative artificial intelligence.* [[ArXiv]](https://arxiv.org/abs/2412.01371/) (2024).
          - **Davide Gallon**, Arnulf Jentzen, Felix Lindner. *Blow up phenomena for gradient descent optimization methods in the training of artificial neural networks.* [[ArXiv]](https://arxiv.org/abs/2211.15641/) (2022).
          
      - layout: top-middle
        title: News
        #link: github.com/sproogen
        # link_text: Project Website
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #quote: >
        #  ...
        description: | # this will include new lines to allow paragraphs
          (March 2025 - September 2025) I am a visiting PhD student at ETH Zurich, under the supervision of [Patrick Cheridito](https://people.math.ethz.ch/~patrickc/). Thank you for this opportunity!
        
          (September 2024) I attended the [Mediterranean Machine Learning Summer School](https://www.m2lschool.org/) in Milan.
          
          (August 2024) I attended the [Deep Learning Theory Summer School](https://mlschool.princeton.edu/) at Princeton.

          (April 2024 - September 2024) I was the teaching assistant for the course [Numerical Optimization](https://studium.uni-muenster.de/qisserver/rds?state=verpublish&status=init&vmfile=no&publishid=409818&moduleCall=webInfo&publishConfFile=webInfo&publishSubDir=veranstaltung) at the University of Münster.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Hitachi Energy
        link: https://www.hitachienergy.com/
        # link_text: boringcompany.com
        sub_title: R&D Data Scientist
        caption: June 2022 - June 2023
        quote: >
         Inspire the next
        description: | # this will include new lines to allow paragraphs
         My primary responsibility was to design and implement innovative solutions to complex data-related problems, working closely with a international team of researchers and engineers.
         One of the major projects I have worked on is the development of a machine learning model to predict transformer's performance. The resulting model was integrated into the company's application.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Padua
        caption: October 2019 - March 2022
        sub_title: Master degree in Mathematical Engineering 
        description: | # this will include new lines to allow paragraphs
          Graduated with 110/110 cum laude.
          I have dedicated my studies to numerical methods for differential equations, dynamic simulations, neural networks for deep learning, numerical methods for big data, stochastic equations.
      - layout: left
        title: University of Padua
        caption: October 2016 - September 2019
        sub_title: Bachelor degree in Mathematics 
        description: | # this will include new lines to allow paragraphs
          The Bachelor in Mathematics program provided me a comprehensive education in theoretical and applied mathematics.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I have a deep interest in staying informed about the latest AI technological advancements.
    

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
